"""System 3 Meta-Cognitive Deliberation, Hyperbolic Manifold, Modal Logic & Active Inference Architecture."""

from .causal import (
    BrittlenessReport,
    CausalCycleError,
    CausalDAG,
    CausalEdge,
    CausalNode,
    CausalNodeNotFoundError,
    CausalNodeType,
    InterventionResult,
)
from .dialectical import (
    AntithesisCritique,
    Contradiction,
    DialecticalSynthesizer,
    EmergentSynthesis,
    ThesisCandidate,
    TRIZContradictionResolver,
    TRIZPrinciple,
    TRIZResolutionRecommendation,
    TRIZ_PRINCIPLES_CATALOG,
)
from .evolution import (
    GENE_ALLELE_OPTIONS,
    PARETO_DIMENSIONS,
    CognitiveGenePool,
    CognitiveGenome,
    create_random_genome,
)
from .executive import (
    CognitiveBiasDetector,
    CognitiveBiasFinding,
    CognitiveBiasType,
    CognitiveGear,
    DynamicSearchHeuristicRewriter,
    SearchHeuristicConfig,
    System3Executive,
    TriLevelArbitrator,
)
from .free_energy import (
    ActiveInferenceEngine,
    FreeEnergyReport,
    GenerativeModel,
    Policy,
    PolicyEvaluation,
    create_default_architecture_pomdp,
)
from .hyperbolic import (
    HyperbolicGeometryError,
    HyperbolicPoint,
    HyperbolicTreeEmbedder,
    PoincareBall,
    TreeEmbeddingNode,
    TreeEmbeddingResult,
)
from .induction import (
    AxiomProvenance,
    AxiomStatus,
    MetaProofInducer,
    NeuroSymbolicAxiom,
)
from .kripke import (
    CTLOperator,
    FormulaNode,
    FormulaParser,
    KripkeModelChecker,
    KripkeStructure,
    KripkeWorld,
    ModelCheckResult,
)
from .oracle import (
    Abort,
    And,
    App,
    Case,
    CurryHowardVerifier,
    Eq,
    Exists,
    Forall,
    FormalProofResult,
    Fst,
    Implies,
    Inl,
    Inr,
    Lam,
    Not,
    Or,
    Pair,
    ProofOracle,
    ProofStatus,
    Prop,
    Refl,
    Snd,
    TacticsEngine,
    Term,
    TermKind,
    Type,
    TypeError,
    TypeKind,
    UndecidabilityDetector,
    Unit,
    UnitTerm,
    Var,
    Void,
)

__all__ = [
    # Causal
    "BrittlenessReport",
    "CausalCycleError",
    "CausalDAG",
    "CausalEdge",
    "CausalNode",
    "CausalNodeNotFoundError",
    "CausalNodeType",
    "InterventionResult",
    # Dialectical
    "AntithesisCritique",
    "Contradiction",
    "DialecticalSynthesizer",
    "EmergentSynthesis",
    "ThesisCandidate",
    "TRIZContradictionResolver",
    "TRIZPrinciple",
    "TRIZResolutionRecommendation",
    "TRIZ_PRINCIPLES_CATALOG",
    # Evolution
    "CognitiveGenePool",
    "CognitiveGenome",
    "GENE_ALLELE_OPTIONS",
    "PARETO_DIMENSIONS",
    "create_random_genome",
    # Induction
    "AxiomProvenance",
    "AxiomStatus",
    "MetaProofInducer",
    "NeuroSymbolicAxiom",
    # Executive
    "CognitiveBiasDetector",
    "CognitiveBiasFinding",
    "CognitiveBiasType",
    "CognitiveGear",
    "DynamicSearchHeuristicRewriter",
    "SearchHeuristicConfig",
    "System3Executive",
    "TriLevelArbitrator",
    # Hyperbolic
    "HyperbolicGeometryError",
    "HyperbolicPoint",
    "HyperbolicTreeEmbedder",
    "PoincareBall",
    "TreeEmbeddingNode",
    "TreeEmbeddingResult",
    # Kripke
    "CTLOperator",
    "FormulaNode",
    "FormulaParser",
    "KripkeModelChecker",
    "KripkeStructure",
    "KripkeWorld",
    "ModelCheckResult",
    # Free Energy
    "ActiveInferenceEngine",
    "FreeEnergyReport",
    "GenerativeModel",
    "Policy",
    "PolicyEvaluation",
    "create_default_architecture_pomdp",
    # Oracle
    "Abort",
    "And",
    "App",
    "Case",
    "CurryHowardVerifier",
    "Eq",
    "Exists",
    "Forall",
    "FormalProofResult",
    "Fst",
    "Implies",
    "Inl",
    "Inr",
    "Lam",
    "Not",
    "Or",
    "Pair",
    "ProofOracle",
    "ProofStatus",
    "Prop",
    "Refl",
    "Snd",
    "TacticsEngine",
    "Term",
    "TermKind",
    "Type",
    "TypeError",
    "TypeKind",
    "UndecidabilityDetector",
    "Unit",
    "UnitTerm",
    "Var",
    "Void",
]
